In [1]:
import numpy as np
import pandas as pd

##### Dataset: Consider the following dataset of sales records:
Order ID Customer Product Category Quantity Price Total Sales
1001 Alice Laptop Electronics 2 800 1600
1002 Bob Phone Electronics 1 500 500
1003 Charlie Chair Furniture 4 100 400
1004 Alice Table Furniture 1 250 250
1005 David Laptop Electronics 1 800 800
1006 Charlie Phone Electronics 2 500 1000
1007 Bob Chair Furniture 2 100 200
1008 Alice Phone Electronics 1 500 500

## 1. Create a DataFrame:
o Load the above dataset into a Pandas DataFrame.

In [2]:
data = {"Order ID": [1001,1002,1003,1004,1005,1006,1007,1008],
    "Customer": ["Alice","Bob","Charlie","Alice","David","Charlie","Bob","Alice"],
    "Product": ["Laptop","Phone","Chair","Table","Laptop","Phone","Chair","Phone"],
    "Category": ["Electronics","Electronics","Furniture","Furniture","Electronics","Electronics","Furniture","Electronics"],
    "Quantity": [2,1,4,1,1,2,2,1],
    "Price": [800,500,100,250,800,500,100,500],
    "Total Sales": [1600,500,400,250,800,1000,200,500]}
df = pd.DataFrame(data)
df

   Order ID Customer Product     Category  Quantity  Price  Total Sales
0      1001    Alice  Laptop  Electronics         2    800         1600
1      1002      Bob   Phone  Electronics         1    500          500
2      1003  Charlie   Chair    Furniture         4    100          400
3      1004    Alice   Table    Furniture         1    250          250
4      1005    David  Laptop  Electronics         1    800          800
5      1006  Charlie   Phone  Electronics         2    500         1000
6      1007      Bob   Chair    Furniture         2    100          200
7      1008    Alice   Phone  Electronics         1    500          500

### 2. Add a New Column:
o Add a column Discount that gives a 10% discount on total
sales.

In [3]:
df["Discount"] = df["Total Sales"] * 0.10
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,Chair,Furniture,4,100,400,40.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0

In [4]:
new_row = {"Order ID": 1009,
    "Customer": "Eve",
    "Product": "Tablet",
    "Category": "Electronics",
    "Quantity": 1,
    "Price": 300,
    "Total Sales": 300}
df.loc[len(df)] = new_row
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,Chair,Furniture,4,100,400,40.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
8,1009,Eve,Tablet,Electronics,1,300,300,NaN

In [5]:
electronics_sales = df[df["Category"] == "Electronics"]
electronics_sales

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
8,1009,Eve,Tablet,Electronics,1,300,300,NaN

### 5. Selection:
o Select the Customer and Total Sales columns.

In [7]:
select=df[['Customer','Total Sales']]
select

  Customer  Total Sales
0    Alice         1600
1      Bob          500
2  Charlie          400
3    Alice          250
4    David          800
5  Charlie         1000
6      Bob          200
7    Alice          500
8      Eve          300

### 6. Grouping:
o Group the data by Customer and calculate the total sales per
customer.

In [11]:
group_sale=df.groupby('Customer')['Total Sales'].sum()
group_sale

Customer
Alice      2350
Bob         700
Charlie    1400
David       800
Eve         300
Name: Total Sales, dtype: int64

### 7. Sorting:
o Sort the DataFrame based on Total Sales in descending
order.

In [12]:
sorted_df = df.sort_values(by="Total Sales", ascending=False)
sorted_df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,Chair,Furniture,4,100,400,40.0
8,1009,Eve,Tablet,Electronics,1,300,300,NaN
3,1004,Alice,Table,Furniture,1,250,250,25.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0

### 8. Apply Function:
o Apply a lambda function to create a new column Sales
Category, where values are labeled as "High" if Total Sales >
1000, otherwise "Low".

In [15]:
df['Sales Category']= df['Total Sales'].apply(lambda x:'High'if x>1000 else'Low')

In [16]:
df.head()

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount,Sales Category
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0,High
1,1002,Bob,Phone,Electronics,1,500,500,50.0,Low
2,1003,Charlie,Chair,Furniture,4,100,400,40.0,Low
3,1004,Alice,Table,Furniture,1,250,250,25.0,Low
4,1005,David,Laptop,Electronics,1,800,800,80.0,Low

### 9. Save DataFrame:
o Save the final DataFrame as a CSV file named sales_data.csv.

In [17]:
df.to_csv("sales_data.csv", index=False)