## Dataframe Introduction
1. Dataframe()
2. Heterogenous
3. Orderd
4. Mutable ,size-Mutable
5. Duplication allowed
6. 2D datastructure of pandas
7. Row and Column

In [33]:
import pandas as pd

In [34]:
df=pd.DataFrame()
type(df)

pandas.DataFrame

In [35]:
df=pd.DataFrame([[101,"abc",50000],[102,"xyz",40000],[103,"pqr",80000]],columns=["ID","Name","Salary"])
df

    ID Name  Salary
0  101  abc   50000
1  102  xyz   40000
2  103  pqr   80000

In [36]:
df["ID"]

0    101
1    102
2    103
Name: ID, dtype: int64

In [37]:
df["Name"]

0    abc
1    xyz
2    pqr
Name: Name, dtype: str

In [38]:
df2=pd.DataFrame({"ID":[101,102,103,104,105,106],"Name":["abc","pqr","xyz","dhe","kowi","kfjir"],"Salary":[60000,50000,40000,4679,54678,34156]})
df2

    ID   Name  Salary
0  101    abc   60000
1  102    pqr   50000
2  103    xyz   40000
3  104    dhe    4679
4  105   kowi   54678
5  106  kfjir   34156

In [39]:
df3=df.set_index("ID")

In [40]:
df3

    Name  Salary
ID
101  abc   50000
102  xyz   40000
103  pqr   80000

In [41]:
df3.loc[101:102]

    Name  Salary
ID
101  abc   50000
102  xyz   40000

In [42]:
df3.iloc[0:2]

    Name  Salary
ID
101  abc   50000
102  xyz   40000

In [43]:
iris=pd.read_csv("C:/Users/DELL/Desktop/FBS/Data analysis/Demos/Datasets-20260831T171242Z-1-001/Datasets/Iris.csv")
iris

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [44]:
iris.tail()

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [45]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [46]:
iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal_Length  150 non-null    float64
 1   Sepal_Width   150 non-null    float64
 2   Petal_Length  150 non-null    float64
 3   Petal_Width   150 non-null    float64
 4   Species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [47]:
iris.describe()

       Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [48]:
iris.head(7)

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa

In [49]:
iris.tail(7)

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [50]:
iris["Sepal_Length"].mean()

np.float64(5.843333333333334)

In [51]:
iris["Sepal_Length"].max()

np.float64(7.9)

In [52]:
iris["Sepal_Length"].agg(["mean","min","max"])

mean    5.843333
min     4.300000
max     7.900000
Name: Sepal_Length, dtype: float64

In [53]:
iris["Species"].unique()

<StringArray>
['Setosa', 'Versicolor', 'Virginica']
Length: 3, dtype: str

In [54]:
iris["Species"].value_counts()

Species
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

In [55]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [56]:
iris.drop("Species",axis=1)

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

## inplace=True
Change in original

In [57]:
iris.drop(0,inplace=True)

In [58]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa