In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("C:/Users/DELL/Desktop/FBS/Data analysis/Demos/Datasets-20260831T171242Z-1-001/Datasets/student_10.csv")
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     str
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), str(1)
memory usage: 532.0 bytes

In [5]:
df.isnull()

    Date  Student ID  Class  Study hrs  Percentage
0  False       False  False      False       False
1  False       False  False      False       False
2  False        True  False      False       False
3  False        True  False      False        True
4  False       False  False      False        True
5  False        True  False      False        True
6  False       False  False      False       False
7  False       False  False       True       False
8  False       False  False       True       False
9  False       False  False      False       False

In [6]:
df.isnull().sum()

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [8]:
df.dropna() # default axis=0 for row

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
9  12-07-2021      1010.0     12        6.0        85.0

In [9]:
# numeric : median and mode
# categarical : mode

In [10]:
med_per=df["Percentage"].median()
med_per

np.float64(80.0)

In [11]:
df["Percentage"]=df["Percentage"].fillna(med_per)

In [12]:
mean_sh=df["Study hrs"].mean()
mean_sh

np.float64(4.375)

In [13]:
df["Study hrs"]=df["Study hrs"].fillna(mean_sh)

In [14]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10      2.000        50.0
1  02-07-2021      1002.0     10      6.000        80.0
2  03-07-2021         NaN     10      3.000        60.0
3  06-07-2021         NaN     11      0.000        80.0
4  07-07-2021      1005.0     11      4.000        80.0
5  08-07-2021         NaN     11     10.000        80.0
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0

In [15]:
df["Student ID"].interpolate()

0    1001.0
1    1002.0
2    1003.0
3    1004.0
4    1005.0
5    1006.0
6    1007.0
7    1008.0
8    1009.0
9    1010.0
Name: Student ID, dtype: float64

In [16]:
df["Student ID"].ffill()

0    1001.0
1    1002.0
2    1002.0
3    1002.0
4    1005.0
5    1005.0
6    1007.0
7    1008.0
8    1009.0
9    1010.0
Name: Student ID, dtype: float64

In [17]:
df["Student ID"].bfill()

0    1001.0
1    1002.0
2    1005.0
3    1005.0
4    1005.0
5    1007.0
6    1007.0
7    1008.0
8    1009.0
9    1010.0
Name: Student ID, dtype: float64

In [18]:
df["Student ID"]=df["Student ID"].interpolate()

In [19]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10      2.000        50.0
1  02-07-2021      1002.0     10      6.000        80.0
2  03-07-2021      1003.0     10      3.000        60.0
3  06-07-2021      1004.0     11      0.000        80.0
4  07-07-2021      1005.0     11      4.000        80.0
5  08-07-2021      1006.0     11     10.000        80.0
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0

In [20]:
df.isnull().sum()

Date          0
Student ID    0
Class         0
Study hrs     0
Percentage    0
dtype: int64

In [21]:
res=df.groupby("Class")

In [22]:
list(res)

[(10,
           Date  Student ID  Class  Study hrs  Percentage
  0  01-07-2021      1001.0     10        2.0        50.0
  1  02-07-2021      1002.0     10        6.0        80.0
  2  03-07-2021      1003.0     10        3.0        60.0),
 (11,
           Date  Student ID  Class  Study hrs  Percentage
  3  06-07-2021      1004.0     11        0.0        80.0
  4  07-07-2021      1005.0     11        4.0        80.0
  5  08-07-2021      1006.0     11       10.0        80.0),
 (12,
           Date  Student ID  Class  Study hrs  Percentage
  6  09-07-2021      1007.0     12      4.000        80.0
  7  10-07-2021      1008.0     12      4.375        90.0
  8  11-07-2021      1009.0     12      4.375        60.0
  9  12-07-2021      1010.0     12      6.000        85.0)]

In [23]:
data=dict(list(res))
data

{10:          Date  Student ID  Class  Study hrs  Percentage
 0  01-07-2021      1001.0     10        2.0        50.0
 1  02-07-2021      1002.0     10        6.0        80.0
 2  03-07-2021      1003.0     10        3.0        60.0,
 11:          Date  Student ID  Class  Study hrs  Percentage
 3  06-07-2021      1004.0     11        0.0        80.0
 4  07-07-2021      1005.0     11        4.0        80.0
 5  08-07-2021      1006.0     11       10.0        80.0,
 12:          Date  Student ID  Class  Study hrs  Percentage
 6  09-07-2021      1007.0     12      4.000        80.0
 7  10-07-2021      1008.0     12      4.375        90.0
 8  11-07-2021      1009.0     12      4.375        60.0
 9  12-07-2021      1010.0     12      6.000        85.0}

In [24]:
data[10]

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021      1003.0     10        3.0        60.0

In [25]:
rec_10=data[10]

In [26]:
rec_10["Percentage"].mean()

np.float64(63.333333333333336)

In [27]:
rec_10["Study hrs"].sum()

np.float64(11.0)

In [28]:
data[11]

         Date  Student ID  Class  Study hrs  Percentage
3  06-07-2021      1004.0     11        0.0        80.0
4  07-07-2021      1005.0     11        4.0        80.0
5  08-07-2021      1006.0     11       10.0        80.0

In [29]:
data[12]

         Date  Student ID  Class  Study hrs  Percentage
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0