In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("C:/Users/DELL/Desktop/FBS/Data analysis/Demos/Datasets-20260831T171242Z-1-001/Datasets/student_10.csv")
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     str
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), str(1)
memory usage: 532.0 bytes

In [6]:
df["Class"]==12

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
Name: Class, dtype: bool

In [7]:
df[df["Class"]==12]

         Date  Student ID  Class  Study hrs  Percentage
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [8]:
df[df["Percentage"]>65]

         Date  Student ID  Class  Study hrs  Percentage
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
9  12-07-2021      1010.0     12        6.0        85.0

In [9]:
df["Student ID"]==1010.0

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: Student ID, dtype: bool

In [11]:
df[df["Student ID"]==1010.0]

         Date  Student ID  Class  Study hrs  Percentage
9  12-07-2021      1010.0     12        6.0        85.0

In [12]:
df.loc[df["Student ID"]==1010.0,"Percentage"]=87.0

In [13]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        87.0

## Concatenate

In [14]:
df1=pd.DataFrame({"Id":[101,102,103],"Name":["abc","xyz","pqr"]})
df1

    Id Name
0  101  abc
1  102  xyz
2  103  pqr

In [16]:
df2=pd.DataFrame({"D_id":[1,2,1],"D_Name":["Hr","Admin","Hr"]})
df2

   D_id D_Name
0     1     Hr
1     2  Admin
2     1     Hr

In [17]:
pd.concat([df1,df2],axis=1)

    Id Name  D_id D_Name
0  101  abc     1     Hr
1  102  xyz     2  Admin
2  103  pqr     1     Hr

In [18]:
pd.concat([df1,df2])

      Id Name  D_id D_Name
0  101.0  abc   NaN    NaN
1  102.0  xyz   NaN    NaN
2  103.0  pqr   NaN    NaN
0    NaN  NaN   1.0     Hr
1    NaN  NaN   2.0  Admin
2    NaN  NaN   1.0     Hr

## Merge

In [21]:
emp=pd.DataFrame({"id":[101,102,103,104],"Name":["abc","xyz","pqr","mno"],"did":[1,2,1,4]})
emp

    id Name  did
0  101  abc    1
1  102  xyz    2
2  103  pqr    1
3  104  mno    4

In [31]:
dept=pd.DataFrame({"did":[1,2,3],"dname":["Admin","IT","Sales"]})
dept

   did  dname
0    1  Admin
1    2     IT
2    3  Sales

In [24]:
pd.merge(emp,dept,how="inner")

    id Name  did  dname
0  101  abc    1  Admin
1  102  xyz    2     IT
2  103  pqr    1  Admin

In [25]:
pd.merge(emp,dept,how="left")

    id Name  did  dname
0  101  abc    1  Admin
1  102  xyz    2     IT
2  103  pqr    1  Admin
3  104  mno    4    NaN

In [26]:
pd.merge(emp,dept,how="right")

      id Name  did  dname
0  101.0  abc    1  Admin
1  103.0  pqr    1  Admin
2  102.0  xyz    2     IT
3    NaN  NaN    3  Sales

In [30]:
pd.merge(emp,dept,left_on="did",right_on="dept_id")

    id Name  did  dept_id  dname
0  101  abc    1        1  Admin
1  102  xyz    2        2     IT
2  103  pqr    1        1  Admin

In [32]:
emp=pd.DataFrame({"id":[101,102,103,104],"Name":["abc","xyz","pqr","mno"],"did":[1,2,1,4]})
emp

    id Name  did
0  101  abc    1
1  102  xyz    2
2  103  pqr    1
3  104  mno    4

In [35]:
dept=pd.DataFrame({"dept_id":[1,2,3],"dname":["Admin","IT","Sales"]})
dept

   dept_id  dname
0        1  Admin
1        2     IT
2        3  Sales

In [36]:
pd.merge(emp,dept,left_on="did",right_on="dept_id")

    id Name  did  dept_id  dname
0  101  abc    1        1  Admin
1  102  xyz    2        2     IT
2  103  pqr    1        1  Admin